### PR TITLE
Changed way to read the key size

### PR DESCRIPTION
**Pull request by Narev**
Changed the way to determine the bytearray size because keys could not be loaded propperly in the Mendix Cloud. Changing the way that the input stream is converted to a bytearray fixes this issue. It does add an extra dependency to commons.io

### CODE REVIEW

**Review by mennodehaas — COMMENTED** [review]
Is it possible to go with this plain Java implementation to prevent an extra dependency?
From [Baeldung](https://www.baeldung.com/convert-input-stream-to-array-of-bytes):

    InputStream is = new ByteArrayInputStream(new byte[] { 0, 1, 2 });
    ByteArrayOutputStream buffer = new ByteArrayOutputStream();
    int nRead;
    byte[] data = new byte[1024];
    while ((nRead = is.read(data, 0, data.length)) != -1) {
        buffer.write(data, 0, nRead);
    }
 
    buffer.flush();
    byte[] byteArray = buffer.toByteArray();

**Comment by mennodehaas** [comment]
Btw. I also forgot to close the InputStream. Always use a try/finally block or try-with-resources statement.

**Comment by Narev** [comment]
Blegh i should not write code at this late hour, but i check your suggestions and they seem to work in the cloud as well so removed the depency of IOUtils

**Comment by mennodehaas** [comment]
Hi @Narev thanks for your updates! I will perform the changes in my own repo, because I see you didn't pull the newest version from the master. In my last release I converted the private key spec from PKCS8 to PKCS1. In your RSAKeyPairReader.java I can see still PKCS8 is being used, which is not appropriate for RSA signed JWTs.

**Pull request closed without merging**
