### PR TITLE
Added functionality for parsing claims as object array

### PR DESCRIPTION
**Pull request by MatthijsDB**
### Change
I've added a piece of code to DecodedJWTParser to enable parsing of claims as an array of objects. To store these objects, I've added the ArrayClaim entity and an association PublicClaimResponse_ArrayClaim.

#### DecodedJWTParser
The code that parses the JWT, will try to get a claim as a list first:
`List<Object> claimList = claim.asList(Object.class);`
If the claim is an array, a PublicClaimResponse object will be created for each of the found objects in the array. If not, the original code continues.  The `value` variable has been renamed to `claimName` for better readability.
#### ArrayClaim
To be able to store the objects found in an array-claim, an entity 'ArrayClaim' was added. One 'ArrayClaim' object is associated with mutilple 'PublicClaimResponse' objects.
#### Mendix version
Upgraded to Mendix 7.16.
#### OAuth JWT library
Updated the Auth0 JWT Java library to version 3.4.1.

### CODE REVIEW

**Comment by mennodehaas** [comment]
Hi @MatthijsDB  thanks for your contribution! I will have a look at it soon.

**Comment by mennodehaas** [comment]
@MatthijsDB just checked your changes. Looks good! As you can see, I included some simple unit tests in the Mendix project to assert the outcome of the Java actions. Can you create a test that demonstrates the functionality of the ArrayClaim and add the new functionality to the README file? Then I can merge and publish.

**Comment by MatthijsDB** [comment]
Hi Menno,

Please check my latest commit.
- Added a page for generating JWTs from UI.
- Added unit tests for JWT generation: A default JWT and a JWT including a ArrayClaim.
- Added proper handling of an ArrayClaim to the GenerateJWT Java action.

I'm going to update the README soon ...

**Comment by mennodehaas** [comment]
Hoi @MatthijsDB, just checked your latest commit. Unfortunately, the project does not compile.
Error in DecodedJWTParser on line 75:
`publicClaimResponse.setPublicClaimResponse_ArrayClaim(context, arrayClaim);`

Few questions:

- Why do you use the DataType enum? 
- I don't get the idea of the ArrayClaim entity. Looks like you make things too complicated here. Does an association between all value containing entitites and the PublicClaim entity make it possible to deal with Array Claims (claims that have values in an array)?
- Why do you commit non-persistable objects in microflows?

**Comment by mennodehaas** [comment]
Array functionality is implemented in latest release.

**Pull request closed without merging**
